### Introduction to Python
#### Date: Sep 06,2023
#### Submission must be made through Github
You are required to complete all tasks correctly (or almost correctly) . You are free to use any material (lecture, Stackoverflow etc.) except full solutions but you should first try to figure them out on your own. We use an nbgrader for partially autograding the assignments. Please DO NOT delete or copy cells. You can add new cells but your solutions should go into the designated cells. 

`range()` practice

1 . Print the numbers between 60 and 69 inclusive.

In [1]:
# Print the numbers between 60 and 69 inclusive
print([i for i in range(60,70)])
# raise NotImplementedError()

[60, 61, 62, 63, 64, 65, 66, 67, 68, 69]


2 . Read numbers until 0 and print their mean and standard deviation without using a list.

In [2]:
# Read numbers until 0 and print their mean and standard deviation without using a list.
my_number = int(input("Enter your number: "))

# Store the enter number
stored_number = my_number
# initialize the  total to 0
total= 0

# initialize the count to 0
count = 0
while my_number >= 0:
    total += my_number
    count += 1
    my_number -= 1

# Evaluate the mean which is the total divided number of times
mean = total / count

# Find the standard deviation
m = 0
while stored_number >= 0:
    m += (stored_number - mean)**2
    stored_number -= 1
    
standard_deviation = (m / count)**(1/2)

# Print the mean
print(f"Mean: {mean}")

# Print the standard deviation
print(f"Standard Deviation: {standard_deviation}")
# raise NotImplementedError()

Enter your number: 5
Mean: 2.5
Standard Deviation: 1.707825127659933


##### Lists
3 . Print the odd numbers from this list. `l = [2, 3, -2, -7, 0, 2, 3]`

In [3]:
l = [2, 3, -2, -7, 0, 2, 3]

print([i for i in l if i % 2 != 0])
# raise NotImplementedError()

[3, -7, 3]


##### Functions
4 . Write a function that takes an integer parameter `(N)` and returns a list of the first `N` prime numbers starting from 2.

In [7]:
def get_n_primes(N):
    if N == 0:
        return []
    primes = [2]
    num = 3 
    while len(primes) < N: 
        is_prime = True 
        for i in range(len(primes)):
            if num % primes[i] == 0: 
                is_prime = False 
                break 
        if is_prime: 
            primes.append(num) 
        num += 2 

    return primes
# raise NotImplementedError()

In [8]:
assert(get_n_primes(3) == [2, 3, 5])
assert(get_n_primes(0) == [])

5. Write a function that takes an integer parameter (N) and returns the Nth Fibonacci number.

 The Fibonacci series is defined as:

$$
F_n = F_{n-1} + F_{n-2} \text{ for } n>1\\
F_0 = 0\\
F_1 = 1
$$

The first few elements of the Fibonacci series are 0, 1, 1, 2, 3, 5, 8, 13 etc.

Raise a `ValueError` if $N<0$.


In [9]:
# Function to get the nth fibonacci number
def get_nth_fibonacci(n):
    
    fn_2 = 0
    fn_1 = 1
    
#     Raise Value error in the provided n is less than 0
    if n < 0:
        raise ValueError("Enter a positive number")
        
    elif n == 1:
        return fn_1
    elif n == 0:
        return fn_2
    elif n == 2:
        return fn_1
    
    for i in range(2,n+1):
        fn = fn_1 + fn_2
        fn_2 = fn_1
        fn_1 = fn
#         Return nth fibonacci number
    return fn_1
# raise NotImplementedError()

In [10]:
assert(get_nth_fibonacci(0) == 0)
assert(get_nth_fibonacci(1) == 1)
assert(get_nth_fibonacci(2) == 1)
assert(get_nth_fibonacci(5) == 5)
assert(get_nth_fibonacci(7) == 13)

try:
    get_nth_fibonacci(-2)
except ValueError:
    pass
else:
    AssertionError("TEST FAILS. Negative index should raise a ValueError.")

6 . Create a function that take a list and a predicate (function with boolean return value) as parameters and returns a new list of those elements which the predicate return True. A predicate is a function that takes one element and return `True` or `False`, for example `is_even`, `is_prime`. If you implemented The following tests should run.


In [15]:
def is_odd(n):
    return n %2 != 0

def is_prime(n):
    if(n==1 or n==0):
            return False
        
    for i in range(2,n):
        if( n% i==0):
            return False
    return True

def filter_list(l, func):
    my_list = []
    for i in l:
        if func(i):
            my_list.append(i)
    return my_list
# raise NotImplementedError()

In [16]:
l1 = [1, 2, 3, 4, 19, 35, 11]
l2 = [1, 4, 9, 16, 25]
assert(filter_list(l1, is_odd) == [1, 3, 19, 35, 11])
assert(filter_list(l1, is_prime) == [2, 3, 19, 11])
assert(filter_list(l2, is_prime) == [])

7.  Reduce is a function that applies a two argument function against an accumulator and each element in the sequence (from left to right) to reduce it to a single value. If no initial value is provided, the accumulator is initialized with the return value of the function run on the first two elements of the sequence.

```
reduce([1, 2, 3], product) ---> 6
reduce([1, 2, 3], product, accumulator=10) ---> 60
reduce(["foo", "bar"], string_addition) ---> "foobar"
reduce(["foo", "bar"], string_addition, accumulator="hello") ---> "hellofoobar"
```

In [18]:

import numpy as np
def reduce(my_list, function, accumulator=None):
    my_list1 = my_list.copy()
    if accumulator != None:
        my_list1.insert(0, accumulator)
        return function(my_list1)
    else:
        return function(my_list1)

def add(list_arg):
    return np.sum(list_arg)

def string_len_add(list_arg):
    length = 0
    for i in list_arg:
        if isinstance(i, int):
            length += i
        else:
            length += len(i)
    return length
# raise NotImplementedError()

In [19]:
l1 = [1, 2, -1, 5]
l2 = ["foo", "bar", "hello"]

assert(reduce(l1, add) == 7)
assert(reduce(l1, add, 10) == 17)
assert(reduce(l2, string_len_add, 0) == 11)

8. Use your reduce function for the following operations:

##### a. count the number of odd elements in a list of integers,
##### b. find the maximum of a list of integers,
##### c. find the longest string in list of strings.

``` Test your solutions. ```

In [21]:
def odd_count(list_arg):
    count = 0
    for i in list_arg:
        if i % 2 != 0:
            count += 1
    return count
# raise NotImplementedError()

6

In [22]:
reduce([1,2,3,4,5,6,7,8,9,0],odd_count)

5

In [23]:
reduce([1,2,3,4,5,6,7,8,9,0],odd_count,5)

6

In [24]:
reduce([1,2,3,4,5,6,7,8,9,0],odd_count)

5

In [25]:
def largest(list_arg):
    return np.amax(list_arg)

def longest(list_arg):
    my_string = ""
    for item in list_arg:
        if len(item) > len(my_string):
            my_string = item
            
    return my_string
# raise NotImplementedError()

In [26]:
reduce([23,45,67,2,45],largest)

67

In [27]:
reduce([23,45,67,2,45],largest,45)

67

In [28]:
reduce([23,45,67,2,45],largest,100)

100

In [29]:
reduce(["song","love","height"],longest)

'height'

In [30]:
reduce(["song","love","height"],longest, "this is a song")

'this is a song'

9. Create a function that takes a matrix of size NxM and returns the pairwise L2 distance of each row pair.

For input $A^{N \times M}$, the output should be $D^{N \times N}$ where: $D_{i,j} = L_2 (A_i, A_j)$

In [40]:
import numpy as np
def pairwise_row_distance(A):
    A = np.array(A, dtype=float)
    num_rows = A.shape[0]
    D = np.zeros((num_rows, num_rows), dtype=float)
    
    for i in range(num_rows):
        for j in range(num_rows):
            D[i][j] = np.sqrt(np.sum((A[i] - A[j]) ** 2))
    return D

def transpose(A):
    return A.T

# raise NotImplementedError()

In [41]:
D = pairwise_row_distance([[1, 0, 2], [0, 2, 1]])
# should be a matrix
# assert is_matrix(D) == True
assert len(D) == 2
assert len(D[0]) == 2
assert D[0][0] == 0
assert abs(D[0][1] - 2.449489742783178) < 1e-3
assert abs(D[1][0] - 2.449489742783178) < 1e-3
assert D[1][1] == 0

# should be symmetric
# assert transpose(D) == D

10 . Object Oriented Programming
 Define a class named `A` with a 'constructor' that takes a single parameter and stores it in an attribute named `value`. Add a `print_value` method to the class. Instantiate the class and call the `print_value` method.

In [31]:
class A:
    def __init__(self, value):
        self.value = value
        
    def print_value(self):
        print(self.value)
a = A(2)
a.print_value()
# raise NotImplementedError()

2


In [32]:
a = A("abc")
a.print_value()

abc


11.  Define a class named `B`, whose `__init__` takes two parameters and stores one in a public attribute and the other in a private attribute named `this_is_public` and `__this_is_private` respectively. Check the class's ``__dict__``  attribute and find out the mangled name of the private attribute.

In [33]:
class B:
    def __init__(self, argument1, argument2):
        self.this_is_public = argument1
        self.__this_is_private = argument2


b = B("This is a good idea", "Love is blind")
print(b.__dict__)
# raise NotImplementedError()

{'this_is_public': 'This is a good idea', '_B__this_is_private': 'Love is blind'}


In [34]:
b = B(1, 2)
assert b.this_is_public == 1
try:
    b.__this_is_private
    print("This should not happen.")
except AttributeError:
    print("Failed to access private attribute, this is good :)")

Failed to access private attribute, this is good :)


13 . Inheritance

###### Guess the output without running the cell.

In [35]:
class A(object): pass
class B(A): pass
class C(A): pass
class D(B): pass

a = A()
b = B()
c = C()
d = D()

print(isinstance(a, object))
print(isinstance(b, object))
print(isinstance(a, B))
print(isinstance(b, A))
print(isinstance(d, A))

True
True
False
True
True


In [36]:
print(issubclass(C, object))
print(issubclass(D, B))
print(issubclass(B, D))
print(issubclass(B, B))

True
True
False
True


#### Create a Cat, a Dog, a Fish and a Eagle class.

The animals have the following attributes:

1. cats, dogs and eagles can make a sound (this should be a make_sound function that prints the animals sound),
2. all animals have an age and a number_of_legs attribute,
3. cats and dogs have a fur_color attribute. They can be instantiated with a single color or a list or tuple of colors.

Use inheritance and avoid repeating code. Use default values in the constructors.

In [11]:
class Animal:
    def __init__(self,name,age=2,number_of_legs=4):
        self.age = age
        self.number_of_legs = number_of_legs
        self.name = name

class Eagle(Animal):
    def __init__(self,name,age=1,number_of_legs=2,sound="fvfgjkffgk"):
        self.sound = sound
        super().__init__(name,age,number_of_legs)
        
    def make_sound(self):
        print(self.sound)

class Cat(Eagle):
    def __init__(self,name,fur=None,age=3,number_of_legs=4,sound="Baaa"):
        self.fur = fur
        super().__init__(name,age,number_of_legs,sound)
        
class Dog(Cat):
    pass

class Fish(Animal):
    pass
# raise NotImplementedError()

In [12]:
try:
    cat = Cat("Fluffy", age=3, fur="white")
    dog = Dog("Cherry", age=1, fur=("white", "brown", "black"))
    fish = Fish("King")
    eagle = Eagle("Bruce", age=2)
    animals = [cat, dog, fish, eagle]
except Exception as e:
    print(f'Could not initialize an animal: {e}')

#### Numpy basic exercises

Use vectorization and avoid for loops in all exercises. Implement each exercise as a single function.

##### Implement standardization for 2D arrays.

Standardization is defined as:

\begin{equation*}
X_{std} = \frac{X - \mu}{\sigma},
\end{equation*}

where $\mu$ is the mean of each row and $\rho$ is the standard deviation of each column.

In [39]:
def standardize(X):
    # YOUR CODE HERE
    import numpy as np

def standardize(matrix):    
    mean = np.mean(matrix, axis=1)
    standard_deviation = np.std(matrix, axis=0)
    standard_matrix = (matrix - mean[:, np.newaxis]) / standard_deviation
    return standard_matrix

X_std = standardize(np.array([[1, 2], [2, 3], [1, 2]]))
X_std

array([[-1.06066017,  1.06066017],
       [-1.06066017,  1.06066017],
       [-1.06066017,  1.06066017]])

#### Implement normalization for 2D arrays.

Normalization is defined as:

\begin{equation*}
X_{norm} = \frac{X - X_{min}}{X_{max} - X_{min}}
\end{equation*}

In [37]:
def normalize(x):
    # YOUR CODE HERE
    min_value = np.min(X, axis=0)
    max_value = np.max(X, axis=0)
    normalized_matrix = (x - min_value) / (max_value - min_value)

    return normalized_matrix

X = np.arange(6).reshape(2, 3)
X[1, 2] = -5
print(X)
normalize(X)

[[ 0  1  2]
 [ 3  4 -5]]


array([[0., 0., 1.],
       [1., 1., 0.]])

In [38]:
answer = np.array(
    [[0., 0., 1.],
     [1., 1., 0.]]
)
X_norm = normalize(X)
assert np.allclose(X_norm, answer)